name: contrail
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  logger: ^2.0.2+1
  get_it: ^7.6.7
  go_router: ^14.1.0
  image_picker: ^1.1.1
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.68.0
  calendar_view: ^1.2.0
  flutter_echarts: ^2.0.0
  flutter_local_notifications: ^17.0.0
  workmanager: ^0.9.0+2
  dav: ^0.2.0
  shared_preferences: ^2.2.2
  uuid: ^4.4.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.0
  build_runner: ^2.4.6
  mocktail: ^1.0.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
